### ISSUE TITLE
why usecase are using flow() 

### ISSUE THREAD

**Issue by periva101** [daniaviladomingo/kmm#3]
I want to thank you first,
then I hope you answer my question, it is a question, not an issue 😃

All ApiService methods are returning suspend functions
  operator fun invoke(param: IN): Flow<Resource<Unit>> = flow {
why are UseCaseIn methods converted to flowOf ()
e.g

```
abstract class UseCaseIn<IN> {
    operator fun invoke(param: IN): Flow<Resource<Unit>> = flow {
        emit(
            try {
                Resource.Success(block(param))
            } catch (ex: Exception) {
                Resource.Error(exception = ex)
            }
        )
    }
    protected abstract val block: suspend (param: IN) -> Unit
}
```
what are the benefits of making all repo methods in kotlin flow,
where consuming suspend fun is easier than flow?
also combing two suspend funs is much easier to combine two flows to create new use cases.

I see this pattern I would like to know the secret behind 😎

**Comment by daniaviladomingo** [comment]
Hi, thanks for your comment,

You're right.
My point is homogenize all UseCase, all flow or all suspend.
As GetCharactersFavoritesUseCase must be a flow (room make this automatically) because I need add or remove favorite update automatically favorites list, then I decided use flow in others uses case. But I totally agree with you, suspend function is easier to use and should be used instead of flow whenever possible.

**Comment by periva101** [comment]
Thank you so so much
